/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ['class', '[data-mode="dark"]'],
    content: ['./src/pages/**/*.{js,ts,jsx,tsx,mdx}', './src/components/**/*.{js,ts,jsx,tsx,mdx}', './src/app/**/*.{js,ts,jsx,tsx,mdx}'],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito Sans', 'Open Sans'],
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
            },
            colors: {
                primary: {
                    light: 'rgb(var(--blue-300))',
                    DEFAULT: 'rgb(var(--blue-500))',
                    dark: 'rgb(var(--blue-700))',
                    25: 'rgb(var(--blue-25))',
                    50: 'rgb(var(--blue-50))',
                    100: 'rgb(var(--blue-100))',
                    200: 'rgb(var(--blue-200))',
                    300: 'rgb(var(--blue-300))',
                    400: 'rgb(var(--blue-400))',
                    500: 'rgb(var(--blue-500))',
                    600: 'rgb(var(--blue-600))',
                    700: 'rgb(var(--blue-700))',
                    800: 'rgb(var(--blue-800))',
                    900: 'rgb(var(--blue-900))',
                },
                'gray-ctr-1': 'rgb(var(--gray-ctr-1))',
                'gray-ctr-2': 'rgb(var(--gray-ctr-2))',
                'gray-ctr-3': 'rgb(var(--gray-ctr-3))',
                'gray-ctr-4': 'rgb(var(--gray-ctr-4))',
                'gray-txt-1': 'rgb(var(--gray-txt-1))',
                'gray-txt-2': 'rgb(var(--gray-txt-2))',
                'gray-txt-3': 'rgb(var(--gray-txt-3))',
                white: 'rgb(var(--white))',
                black: 'rgb(var(--black))',
                gray: {
                    25: 'rgb(var(--gray-25))',
                    50: 'rgb(var(--gray-50))',
                    100: 'rgb(var(--gray-100))',
                    200: 'rgb(var(--gray-200))',
                    300: 'rgb(var(--gray-300))',
                    400: 'rgb(var(--gray-400))',
                    500: 'rgb(var(--gray-500))',
                    600: 'rgb(var(--gray-600))',
                    700: 'rgb(var(--gray-700))',
                    800: 'rgb(var(--gray-800))',
                    900: 'rgb(var(--gray-900))',
                },
                blue: {
                    25: 'rgb(var(--blue-25))',
                    50: 'rgb(var(--blue-50))',
                    100: 'rgb(var(--blue-100))',
                    200: 'rgb(var(--blue-200))',
                    300: 'rgb(var(--blue-300))',
                    400: 'rgb(var(--blue-400))',
                    500: 'rgb(var(--blue-500))',
                    600: 'rgb(var(--blue-600))',
                    700: 'rgb(var(--blue-700))',
                    800: 'rgb(var(--blue-800))',
                    900: 'rgb(var(--blue-900))',
                },
                red: {
                    25: 'rgb(var(--red-25))',
                    50: 'rgb(var(--red-50))',
                    100: 'rgb(var(--red-100))',
                    200: 'rgb(var(--red-200))',
                    300: 'rgb(var(--red-300))',
                    400: 'rgb(var(--red-400))',
                    500: 'rgb(var(--red-500))',
                    600: 'rgb(var(--red-600))',
                    700: 'rgb(var(--red-700))',
                    800: 'rgb(var(--red-800))',
                    900: 'rgb(var(--red-900))',
                },
                yellow: {
                    25: 'rgb(var(--yellow-25))',
                    50: 'rgb(var(--yellow-50))',
                    100: 'rgb(var(--yellow-100))',
                    200: 'rgb(var(--yellow-200))',
                    300: 'rgb(var(--yellow-300))',
                    400: 'rgb(var(--yellow-400))',
                    500: 'rgb(var(--yellow-500))',
                    600: 'rgb(var(--yellow-600))',
                    700: 'rgb(var(--yellow-700))',
                    800: 'rgb(var(--yellow-800))',
                    900: 'rgb(var(--yellow-900))',
                },
                green: {
                    25: 'rgb(var(--green-25))',
                    50: 'rgb(var(--green-50))',
                    100: 'rgb(var(--green-100))',
                    200: 'rgb(var(--green-200))',
                    300: 'rgb(var(--green-300))',
                    400: 'rgb(var(--green-400))',
                    500: 'rgb(var(--green-500))',
                    600: 'rgb(var(--green-600))',
                    700: 'rgb(var(--green-700))',
                    800: 'rgb(var(--green-800))',
                    900: 'rgb(var(--green-900))',
                },
            },
        },
    },
    plugins: [],
};
